### ISSUE TITLE
Configuration file is missing in your repo

### ISSUE THREAD

**Issue by tecbird** [passioneight/pimcore-options-providers#1]
See in your File: PimcoreOptionsProvidersExtension you use follwing line, but the file does not exists!

https://github.com/passioneight/pimcore-options-providers/blob/d0b89a7c47d0adbabb99b1186ec37495e74b3fed/src/DependencyInjection/PimcoreOptionsProvidersExtension.php#L9

use Passioneight\Bundle\PimcoreOptionsProvidersBundle\Constant\Configuration as Config;

**Comment by passioneight** [comment]
Apologies, not sure how we missed that one. Update incoming :-)

**Comment by tecbird** [comment]
Sweet! Please check another change i have to made, because field can be an empty string:
https://github.com/tecbird/pimcore-options-providers/commit/9938e7a3f54216ddf1f0a18f32330ceabc2871be

would be nice if you can fix this also, then i can delete the fork

thanks!

**Comment by passioneight** [comment]
I'll have a look some time tomorrow - may I ask you to open another issue for this?

**Comment by tecbird** [comment]
Great, see here: https://github.com/passioneight/pimcore-options-providers/issues/2

**Comment by passioneight** [comment]
Thanks!
