### ISSUE TITLE
Please check for empty string, otherwise json error occure

### ISSUE THREAD

**Issue by tecbird** [passioneight/pimcore-options-providers#2]
If "$optionsProviderData" variable is an empty string, a json error occure (on call json_decode).
Please add an check for this case.

https://github.com/passioneight/pimcore-options-providers/blob/738df013b420ccfbfcb55e0b688f85f945ae28b6/src/Service/Backend/OptionsProvider/AbstractOptionsProvider.php#L60

thanks!

**Comment by passioneight** [comment]
@tecbird which Pimcore version are you using? Also, if you use your options provider programatically, please provide a snippet of your code.

**Comment by passioneight** [comment]
@tecbird any chance you can provide the information needed?

**Comment by passioneight** [comment]
@tecbird I'm closing this issue, since you are not responding anymore.

Currently, my best guess is that you are providing the `$optionsProviderData` programmatically (using `$context`). In this case, please ensure that `$context` is an `array`.
